"""Recompute the large-number companion answers and verify generated byte closure.

This narrow executable check does not replace Tamil or learner/AT review.
"""
from collections import Counter
import json
import re
import xml.etree.ElementTree as ET

import build_large_numbers as build
from build_u002 import require

H = build.H
ATOMS = {"ஒரு": 1, "ஒன்று": 1, "இரண்டு": 2, "மூன்று": 3, "நான்கு": 4,
         "ஐந்து": 5, "ஆறு": 6, "ஏழு": 7, "எட்டு": 8, "ஒன்பது": 9,
         "பன்னிரண்டு": 12, "இருபது": 20, "முப்பது": 30, "நாற்பது": 40,
         "நாற்பத்து": 40, "அறுபது": 60, "நானூற்று": 400}
SCALES = {"ஆயிரம்": 10**3, "மில்லியன்": 10**6, "பில்லியன்": 10**9, "டிரில்லியன்": 10**12}


def text(node):
    return "".join(node.itertext())


def first_para(node):
    return text(node.find(f"{{{H}}}p"))


def numbers(value):
    return re.findall(r"[0-9]+(?:,[0-9]{3})*", value)


def integer(value):
    return int(value.replace(",", ""))


def parse_name(name):
    """Narrow coefficient+scale parser, not whole-answer lookup strings."""
    result, last_scale = 0, 10**15
    for group in name.split(","):
        words = group.strip().split()
        require(words, "Empty name group")
        scale = SCALES.get(words[-1], 1)
        coefficients = words[:-1] if scale > 1 else words
        require(all(word in ATOMS for word in coefficients), f"Unreviewed Tamil coefficient: {group}")
        coefficient = sum(ATOMS[word] for word in coefficients)
        require(0 < coefficient < 1000 and scale < last_scale, "Invalid name group or scale order")
        result += coefficient * scale
        last_scale = scale
    return result


def check_answers(root):
    build.validate_companion(root)
    by_id = {n.get("id"): n for n in root.iter() if n.get("id")}
    q = lambda key: first_para(by_id["ta-large-" + key])
    a = lambda key: first_para(by_id["ta-large-" + key + "-answer"])
    checked = {}
    for key in ("D1", "P1", "M1", "T1"):
        expected = format(integer(numbers(q(key))[0]), ",")
        require(a(key).startswith(expected + "."), f"Grouping answer mismatch: {key}")
        checked[key] = {"grouped": expected}
    for key in ("D4", "P4", "M4", "T4"):
        name = re.search("“([^”]+)”", q(key)).group(1)
        expected = parse_name(name)
        actual = integer(numbers(a(key))[0])
        require(actual == expected, f"Word-to-digit answer mismatch: {key}")
        checked[key] = {"parsed_name_value": expected}
    for key in ("P3", "M3", "T3"):
        expected = integer(numbers(q(key))[0])
        answer = a(key)
        name = answer.split("பெயர்: ", 1)[1].split(".", 1)[0] if "பெயர்: " in answer else answer.split(".", 1)[0]
        require(parse_name(name) == expected, f"Digit-to-name answer mismatch: {key}")
        checked.setdefault(key, {})["parsed_answer_name"] = expected
    for key, digits in (("D2", (5,)), ("P2", (4, 6)), ("M2", (2, 0)), ("T2", (4, 0))):
        numeral = numbers(q(key))[0].replace(",", "")
        claims = re.findall(r"([0-9]) (நூறாயிரங்கள்|ஆயிரங்கள்) இடத்தில் உள்ளது; அதன் மதிப்பு ([0-9,]+)", a(key))
        if key == "D2":
            # D2 begins with the place rather than repeating the requested digit.
            require(a(key).startswith("நூறாயிரங்கள் இடம்; மதிப்பு "), "D2 place label changed")
            claims = [("5", "நூறாயிரங்கள்", numbers(a(key))[0])]
        require(len(claims) == len(digits), f"Missing place/value claims: {key}")
        for (digit, label, contribution), expected_digit in zip(claims, digits):
            require(int(digit) == expected_digit and numeral.count(digit) == 1, f"Ambiguous digit: {key}")
            power = len(numeral) - numeral.index(digit) - 1
            require(power == {"நூறாயிரங்கள்": 5, "ஆயிரங்கள்": 3}[label], f"Wrong place label: {key}")
            require(integer(contribution) == expected_digit * 10**power, f"Wrong contribution: {key}")
        checked[key] = {"place_value_claims": len(claims)}
    for key, left, normalized, deleted, digit in (
        ("D3", "0073", "73", "273005", "2"),
        ("M3", "008040006", "8040006", "840006", "8"),
        ("T3", "005060004", "5060004", "560004", "5"),
    ):
        if key == "D3":
            require(numbers(q(key)) == ["0073", "73", "2,073,005", "073", "0", "273005", "2"],
                    "D3 source comparison numerals changed")
        require(integer(left) == integer(normalized), "Bad normalization fixture")
        original = "2073005" if key == "D3" else normalized
        require(integer(original) != integer(deleted), "Deletion should change value")
        original_contribution = int(digit) * 10**(len(original) - 1)
        deleted_contribution = int(digit) * 10**(len(deleted) - 1)
        require(format(original_contribution, ",") in a(key) and format(deleted_contribution, ",") in a(key),
                f"Missing zero-deletion contribution explanation: {key}")
        require(format(integer(deleted), ",") in a(key), f"Missing changed numeral: {key}")
        checked.setdefault(key, {})["zero_deletion_changes_value"] = True
    guide = by_id["ta-large-place-guide"].find(f"{{{H}}}tbody")
    require(len(guide) == 15, "Place guide row count changed")
    for power, row in enumerate(guide):
        require(integer(text(row[1])) == 10**power, "Place guide value mismatch")
    scale_rows = by_id["ta-large-scales"].find(f"{{{H}}}tbody")
    require([integer(text(row[1])) for row in scale_rows] == [10**p for p in (0, 3, 6, 9, 12)], "Scale values mismatch")
    require(text(by_id["ta-large-zero-chart"]).count("காலி") == 8, "Leading blank count changed")
    require(set(checked) == {f"{prefix}{i}" for prefix in "DPMT" for i in range(1, 5)}, "Not all sixteen items checked")
    return checked


def main():
    root = ET.parse(build.COMPANION).getroot()
    checked = check_answers(root)
    # Four actual XML mutations must be rejected; inputs are never edited.
    original = build.COMPANION.read_text(encoding="utf-8")
    mutations = (original.replace("4,807,316.", "4,807,317.", 1),
                 original.replace("3,005,042,007.", "3,005,042,008.", 1),
                 original.replace("ஏழு மில்லியன், இருபது ஆயிரம், நானூற்று ஆறு.", "ஏழு மில்லியன், இருபது ஆயிரம், நானூற்று ஐந்து.", 1),
                 original.replace('data-answer-for="ta-large-D1"', 'data-answer-for="ta-large-D2"', 1))
    for changed in mutations:
        require(changed != original, "QA mutation did not change the input")
        try:
            check_answers(ET.fromstring(changed))
        except ValueError:
            continue
        raise ValueError("Invalid companion passed arithmetic QA")
    payload, manifest = build.build_payload()
    require(all((build.OUTPUT / name).is_file() and (build.OUTPUT / name).read_bytes() == data
                for name, data in payload.items()), "Reader files do not match the current build")
    receipt = {"scope": "U003-U005 recovery segment", "status": "arithmetic-and-structure-pass-not-linguistic-certification",
               "companion_sha256": build.review.sha(build.COMPANION),
               "html_sha256": build.review.digest(payload["index.html"]),
               "epub_sha256": build.review.digest(payload[build.EPUB_NAME]),
               "counts": manifest["counts"], "checked_questions": checked,
               "negative_tests": 4, "limits": ["Narrow Tamil coefficient parser covers these seven authored names, not arbitrary Tamil prose.",
                                                    "Full answer wording and independent learning/AT outcomes still require human review."]}
    path = build.LANG / "qa/LARGE_NUMBER-structural-receipt.json"
    path.write_text(json.dumps(receipt, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"status": receipt["status"], "questions": len(checked), "negative_tests": 4}, indent=2))


if __name__ == "__main__":
    main()
