"""New deterministic U025 plot of P(x)=2x^3-50x, not a source image.

Pillow renders the mathematical plot with a local Unicode font, following the
existing U015 renderer pattern. No downloads or source images are used.
Default prints metadata only. --write writes ONLY the authorized PNG path.
--check compares regenerated bytes with that existing PNG, without writes.
Byte reproducibility assumes the recorded Pillow version and font bytes.
"""
from hashlib import sha256
from io import BytesIO
from pathlib import Path
import argparse
import json
import math
from PIL import Image, ImageDraw, ImageFont, __version__ as PILLOW_VERSION

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets/A30-U025-radicand-sign.png"
WINDOW = (-6, 6, -140, 140)
ZEROS = (-5, 0, 5)


def radicand(x):
    return 2 * x ** 3 - 50 * x


def find_font():
    for candidate in (Path("C:/Windows/Fonts/arial.ttf"),
                      Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")):
        if candidate.is_file():
            return candidate
    raise FileNotFoundError("Supply --font with an existing Unicode TrueType font.")


def curve_points():
    # All three exact zeros occur among these samples. The sign proof is textual.
    return [(k / 100, radicand(k / 100)) for k in range(-600, 601)]


def render_png(font_path):
    width, height, scale = 640, 640, 2
    image = Image.new("RGB", (width * scale, height * scale), "white")
    draw = ImageDraw.Draw(image)
    fonts = {size: ImageFont.truetype(str(font_path), size * scale)
             for size in (17, 18, 20, 22)}
    left, top, right, bottom = 85, 105, 603, 418
    xmin, xmax, ymin, ymax = WINDOW
    sx = lambda x: left + (x - xmin) / (xmax - xmin) * (right - left)
    sy = lambda y: bottom - (y - ymin) / (ymax - ymin) * (bottom - top)

    def line(points, fill="#162536", thickness=1):
        draw.line([(round(x * scale), round(y * scale)) for x, y in points],
                  fill=fill, width=thickness * scale)

    def text(x, y, value, size=18, anchor="mm", fill="#162536"):
        draw.text((round(x * scale), round(y * scale)), value,
                  font=fonts[size], fill=fill, anchor=anchor)

    def arrow(start, end, fill="#176a93", length=12):
        line([start, end], fill, 3)
        angle = math.atan2(end[1] - start[1], end[0] - start[0])
        points = [end,
                  (end[0] - length * math.cos(angle - .45),
                   end[1] - length * math.sin(angle - .45)),
                  (end[0] - length * math.cos(angle + .45),
                   end[1] - length * math.sin(angle + .45))]
        draw.polygon([(round(x * scale), round(y * scale)) for x, y in points], fill=fill)

    text(320, 25, "Đồ thị bổ sung — Bài 26", 22)
    text(320, 57, "P(x) = 2x³ − 50x", 22)
    text(320, 84, "Biểu thức dưới căn; không phải đồ thị của f", 17)
    draw.rectangle((left * scale, top * scale, right * scale, bottom * scale),
                   outline="#b7c5ce", width=scale)
    for x in range(-6, 7):
        line([(sx(x), top), (sx(x), bottom)], "#e0e7ec")
        if x in (-6, -5, -3, 0, 3, 5, 6):
            text(sx(x), bottom + 20, str(x).replace("-", "−"), 17)
    for y in (-100, -50, 0, 50, 100):
        line([(left, sy(y)), (right, sy(y))], "#e0e7ec")
        text(left - 12, sy(y), str(y).replace("-", "−"), 17, anchor="rm")
    line([(left, sy(0)), (right + 12, sy(0))], "#273e50", 2)
    line([(sx(0), bottom), (sx(0), top - 5)], "#273e50", 2)
    text(right + 17, sy(0) + 21, "x", 18)
    text(sx(0) + 20, top + 12, "P(x)", 17, anchor="lm")
    points = curve_points()
    line([(sx(x), sy(y)) for x, y in points], "#176a93", 3)
    arrow((sx(5.78), sy(radicand(5.78))), (sx(6), sy(radicand(6))))
    arrow((sx(-5.78), sy(radicand(-5.78))), (sx(-6), sy(radicand(-6))))
    for x in ZEROS:
        cx, cy, radius = sx(x), sy(0), 5
        draw.ellipse(((cx - radius) * scale, (cy - radius) * scale,
                      (cx + radius) * scale, (cy + radius) * scale), fill="#162536")
        # Put the origin label below-left, away from the descending curve.
        text(cx - (12 if x == 0 else 0), cy + (18 if x == 0 else -18), str(x).replace("-", "−"), 18,
             anchor="rm" if x == 0 else "mm")
    text(320, 464, "Dấu của P(x) — chú giải, không thuộc đồ thị", 17)
    edges = [52, 186, 320, 454, 588]
    for a, b, label, sign in zip(edges, edges[1:],
                                ("(−∞,−5)", "(−5,0)", "(0,5)", "(5,∞)"),
                                ("−", "+", "−", "+")):
        draw.rectangle((a * scale, 485 * scale, b * scale, 548 * scale),
                       outline="#b7c5ce", width=scale)
        text((a + b) / 2, 503, label, 18)
        text((a + b) / 2, 531, sign, 20)
    text(320, 570, "P(−5) = P(0) = P(5) = 0", 20)
    text(320, 601, "Mũi tên: đường cong còn tiếp tục ngoài khung.", 17)
    text(320, 623, "Khung: −6 ≤ x ≤ 6; −140 ≤ y ≤ 140.", 17)
    output = BytesIO()
    image.save(output, format="PNG", compress_level=9, optimize=False)
    return output.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    font = args.font or find_font()
    data = render_png(font)
    expected = (ROOT / "assets/A30-U025-radicand-sign.png").resolve()
    assert OUTPUT.resolve() == expected and expected.parent == (ROOT / "assets").resolve()
    if args.write:
        assert expected.parent.is_dir(), "existing authorized assets directory required"
        expected.write_bytes(data)
    if args.check:
        assert expected.read_bytes() == data, "PNG bytes differ from this renderer/font environment"
    print(json.dumps({"output":str(OUTPUT), "sha256":sha256(data).hexdigest(),
                      "bytes":len(data), "pixels":[1280,1280], "pillow_version":PILLOW_VERSION,
                      "font":str(font), "font_sha256":sha256(font.read_bytes()).hexdigest(),
                      "plot_window":WINDOW, "zeros":ZEROS, "sample_count":len(curve_points()),
                      "new_supplement_not_source_image":True,
                      "wrote":args.write, "checked":args.check}, ensure_ascii=True, indent=2))


if __name__ == "__main__":
    main()
