"""Source-ID-bound records from complete prose and 26-original-image review."""
from pathlib import Path
import xml.etree.ElementTree as E
import json
from inspect_a10_m82459 import SRC,C,flat
r=E.parse(SRC).getroot();ids={e.get('id'):e for e in r.iter()if e.get('id')};entries={}
def add(i,issue,gu,**extra):
 e=ids[i]
 entries[i]={'source_issue':issue,'correction_gu':gu,'rationale':'Independently read pinned English source and, where named, actual original image. Source mathematical tokens and lists remain unchanged.','original_evidence':e.get('alt')or' '.join(flat(e).split()),**extra}
 if e.find(C+'image')is not None:entries[i]['source_image']=e.find(C+'image').get('src')
def alt(i,issue,gu):add(i,issue,gu,alt_gu=gu)
alt('fs-id1170655170188','The original nested-set diagram prints category names only; the source alternative invents displayed example-number lists.','વાસ્તવિક સંખ્યાઓનો મોટો વાદળી લંબચોરસ છે. અંદર ડાબે નારંગી ભાગ સંમેય સંખ્યાઓનો અને જમણે આછો લીલો-વાદળી ભાગ અસંમેય સંખ્યાઓનો છે. સંમેય સંખ્યાઓની અંદર પૂર્ણાંકોનો લંબચોરસ, તેની અંદર પૂર્ણ સંખ્યાઓનો અને તેની અંદર લાલ રંગનો ગણતરીની સંખ્યાઓનો લંબચોરસ છે. આકૃતિમાં આ સમૂહોનાં નામ છે; ઉદાહરણ સંખ્યાઓની યાદી છાપેલી નથી.')
alt('fs-id1170655114295','The original002 has eight plotted values including7/4, omitted by its alt;4/5 is an extra plotted value not in the seven-value source instruction.','સંખ્યારેખા −6થી 6 સુધી છે. ડાબેથી જમણે આઠ બિંદુઓ છે: −5, −9/2, −4/5, 1/5, 4/5, 7/4, 8/3 અને 3. −9/2 એ −5 અને −4ની બરાબર વચ્ચે છે. −4/5 એ −1ની થોડે જમણે છે. 1/5 એ 0ની થોડે જમણે અને 4/5 એ 1ની થોડે ડાબે છે. 7/4 એ 1 અને 2ની વચ્ચે, 2ની વધુ નજીક છે. 8/3 એ 2 અને 3ની વચ્ચે, 3ની વધુ નજીક છે. મૂળ સૂચિમાં ન હોય તેવું વધારાનું 4/5 બિંદુ પણ આકૃતિમાં છે.')
alt('fs-id1170655192776','Source alt says no points; actual015 has four colored points.','સંખ્યારેખા −10થી 0 સુધી છે અને દરેક પૂર્ણાંક પાસે આંક છે. −9 અને −6 પર આછાં લીલાં-વાદળી બિંદુઓ છે; −3 અને −2 પર લાલ બિંદુઓ છે. −2નું સ્થાન −3ની જમણે છે અને −9નું સ્થાન −6ની ડાબે છે.')
alt('fs-id1170655029517','Source alt calls the first label negative0.0; actual013 prints0.0.','સંખ્યારેખા 0.0થી 1.0 સુધી છે. ડાબેથી જમણે 0.04 અને 0.4 બિંદુઓ ચિહ્નિત છે. 0.04 બિંદુ 0.0 અને 0.1ની વચ્ચે છે. 0.4 બિંદુ 0.3 અને 0.5ની વચ્ચે છે.')
add('fs-id1170654963334','Actual010 uses intervals of0.02, not one mark for every hundredth as the prose could suggest.','આકૃતિમાં −1.00થી 0.00 સુધી દરેક નાનો ભાગ 0.02નો છે; મોટા અંક 0.10ના અંતરે છે. −0.74નું બિંદુ −0.80થી 0.06 જમણે, એટલે ત્રણ નાના ભાગ પછી આવે છે.')
add('fs-id1170654872607','Generic positive-square-root definition excludes zero despite the immediately preceding n>=0 condition.','મુખ્ય વર્ગમૂળ અનઋણ હોય છે: ધન સંખ્યાનું મુખ્ય વર્ગમૂળ ધન છે અને 0નું મુખ્ય વર્ગમૂળ 0 છે.',text_replacements_gu={'એ એવી ધન સંખ્યા છે જેનો વર્ગ':'એ એવી અનઋણ સંખ્યા છે જેનો વર્ગ'})
add('fs-id1166424761150','Glossary defines the radical as positive without the zero case.','વર્ગમૂળચિહ્ન મુખ્ય, એટલે અનઋણ વર્ગમૂળ દર્શાવે છે. શૂન્યનું વર્ગમૂળ શૂન્ય છે.',text_replacements_gu={'ચિહ્ન, જે ધન વર્ગમૂળ દર્શાવે છે.':'ચિહ્ન, જે મુખ્ય, એટલે અનઋણ વર્ગમૂળ દર્શાવે છે.'})
add('fs-id1170655203491','Source calls3 and−5 whole numbers although−5 is an integer, not a whole number.','3 અને −5 બંને પૂર્ણાંક છે. તેમાં 3 પૂર્ણ સંખ્યા પણ છે; −5 પૂર્ણ સંખ્યા નથી.',text_replacements_gu={'આ પૂર્ણ સંખ્યાઓનાં સ્થાન':'આ પૂર્ણાંકોનાં સ્થાન'})
add('fs-id1170654963379','Source says the previous number line had only positive and negative integers, omitting zero.','અગાઉની સંખ્યારેખા પર ધન પૂર્ણાંક, ઋણ પૂર્ણાંક અને શૂન્ય હતા.',text_replacements_gu={'માત્ર ધન અને ઋણ પૂર્ણાંક હતા':'ધન પૂર્ણાંક, ઋણ પૂર્ણાંક અને શૂન્ય હતા'})
add('fs-id1170655215831','Improper-fraction explanation needs explicit sign scope for−9/2 and equality in its general definition.','આ ઉદાહરણમાં −9/2નો ઋણ ચિહ્ન બહાર છે; તેના અપૂર્ણાંક ભાગ 9/2માં 9 > 2 છે. સામાન્ય રીતે ધન છેદ ધરાવતા અપૂર્ણાંક માટે અંશનું નિરપેક્ષ મૂલ્ય છેદ જેટલું કે વધુ હોય તો અપૂર્ણાંક અશુદ્ધ કહેવાય.')
add('eip-313','Worked inequality rows(b)and(c) say right although both original006 positions and final inequalities show left.','ⓑ −3 પૂર્ણ 1/2નું સ્થાન −3ની ડાબે છે, એટલે −3 પૂર્ણ 1/2 < −3. ⓒ −3/4નું સ્થાન −1/4ની ડાબે છે, એટલે −3/4 < −1/4. ⓐ અને ⓓમાં “જમણે” સાચું છે.',entry_direction_overrides_gu={'1':'ડાબે','2':'ડાબે'})
add('fs-id1170655098623','After introducing irrational decimal forms, the assertion that decimals are fractions needs its terminating-decimal context.','અહીં સંખ્યારેખા પર દર્શાવેલી દશાંશ સંખ્યાઓ સમાપ્ત દશાંશ છે અને તેમને પૂર્ણાંકોના અપૂર્ણાંક તરીકે લખી શકાય છે. દરેક દશાંશ સ્વરૂપ સંમેય હોતું નથી.',text_replacements_gu={'દશાંશ સંખ્યાઓ અપૂર્ણાંકનાં સ્વરૂપ હોવાથી':'અહીં લીધેલી સમાપ્ત દશાંશ સંખ્યાઓ અપૂર્ણાંકનાં સ્વરૂપ હોવાથી'})
add('fs-id1170655081279','English prose typo says write1 and1.0 rather than write1 as1.0.','અહીં 0ને 0.0 અને 1ને 1.0 તરીકે લખવાનાં છે, જેથી દરેક સંખ્યા દશાંશ સુધી દર્શાવાય.')
for i in ['fs-id1166422524060','fs-id1170654942859']:
 add(i,'Decimal comparison must equalize fractional decimal places, not total digit counts; signed examples require integers rather than ignoring minus signs as whole numbers.','દશાંશબિંદુ પછીનાં સ્થાનોની સંખ્યા સરખી કરો. પછી બંને સંખ્યાનાં દશાંશબિંદુ દૂર કરતાં મળતા પૂર્ણાંકોની સરખામણી કરો; ઋણ ચિહ્નો જાળવો.',text_replacements_gu={'બંને સંખ્યાઓમાં અંકોની સંખ્યા સરખી છે કે નહીં તે તપાસો. સરખી ન હોય તો ઓછા અંકવાળી સંખ્યાના અંતે શૂન્ય લખીને સરખી કરો.':'બંને સંખ્યાઓમાં દશાંશબિંદુ પછીનાં સ્થાનોની સંખ્યા સરખી છે કે નહીં તે તપાસો. સરખી ન હોય તો ઓછાં દશાંશસ્થાનોવાળી સંખ્યાના અંતે શૂન્ય લખીને સરખી કરો.','સંખ્યાઓ પૂર્ણ સંખ્યા હોય તેમ તેમની સરખામણી કરો.':'બંને દશાંશબિંદુ દૂર કરતાં મળતા પૂર્ણાંકોની સરખામણી કરો; ઋણ ચિહ્નો જાળવો.'})
ex=list(r.iter(C+'exercise'))
for j in [9,10,11,20,58,59,60,61,70]:
 add(ex[j].get('id'),'Irrationality cannot be determined from a finite decimal prefix followed only by an ellipsis; source assumes a nonterminating nonrepeating continuation.','અહીં અસંમેય ગણાતી દશાંશ સંખ્યા અંત વિના અને કોઈ નિશ્ચિત અંકસમૂહનું આવર્તન થયા વિના આગળ વધે છે એમ સ્ત્રોત માને છે. માત્ર દેખાતા અંકો અને “…” પરથી તે સાબિત થતું નથી; આગળ વધવાનો નિયમ અથવા આ સ્પષ્ટ શરત જરૂરી છે. આ શરત સાથે જ સ્ત્રોતનું અસંમેય તરીકેનું વર્ગીકરણ માન્ય છે.')
add('fs-id1166422870658','Source appends an ellipsis to the rounded nine-place decimal3.141592654 and uses equality; this is not the actual initial digit sequence of pi.','પાઈનું દશાંશ સ્વરૂપ π = 3.141592653589793… છે. નવ દશાંશસ્થાન સુધી નજીકની કિંમત π ≈ 3.141592654 લખી શકાય. નજીકની કિંમત પછી “…” મૂકી તેને ચોક્કસ દશાંશ વિસ્તાર તરીકે લખવું યોગ્ય નથી.',verification_source='https://dlmf.nist.gov/draft1/3.12#E1')
data={'schema':'gujarati-source-errata-v1','book':'A10','module':'m82459','source_mathematical_tokens_unchanged':True,'entries':entries}
Path(__file__).with_name('a10-m82459-errata.gu.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(len(entries),'explicit source errata/clarifications')
